/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CliDeviceStatus = "approved" | "consumed" | "denied" | "expired" | "pending";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type InvoiceEventType = "created" | "downloaded" | "email_failed" | "emailed" | "finalized" | "paid" | "updated" | "viewed" | "voided";

export type InvoiceStatus = "draft" | "open" | "paid" | "void";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export interface ApiKeys {
  created_at: Generated<string>;
  expires_at: string | null;
  id: Generated<string>;
  last_used_at: string | null;
  name: string;
  owner_id: string;
  /**
   * Public identifier, e.g. inv_live_ab12cd34. Greppable on purpose so a leaked key is detectable.
   */
  prefix: string;
  /**
   * Set instead of deleting the row, so the audit log can still name the key that made past requests.
   */
  revoked_at: string | null;
  scopes: Generated<string[]>;
  secret_hash: string;
}

export interface ApiRequests {
  api_key_id: string | null;
  client_id: string | null;
  created_at: Generated<string>;
  duration_ms: number;
  id: Generated<string>;
  idempotency_key: string | null;
  ip_hash: string | null;
  method: string;
  owner_id: string;
  request_id: string;
  route: string;
  status: number;
  via: string;
}

export interface Businesses {
  account_name: string | null;
  account_number: string | null;
  address_line1: string | null;
  address_line2: string | null;
  bank_name: string | null;
  business_type: string | null;
  city: string | null;
  country: Generated<string>;
  /**
   * ISO 3166-1 alpha-2.
   */
  country_code: Generated<string>;
  created_at: Generated<string>;
  /**
   * ISO 4217 default invoice currency.
   */
  currency: Generated<string>;
  default_notes: string | null;
  default_terms: string | null;
  email: string | null;
  gst_constitution: string | null;
  /**
   * Verbatim Search GSTIN response from the Sandbox API at the time of prefill.
   */
  gst_data: Json | null;
  gst_fetched_at: string | null;
  gst_registered_on: string | null;
  gst_status: string | null;
  gstin: string | null;
  id: Generated<string>;
  ifsc: string | null;
  invoice_prefix: Generated<string>;
  is_gst_registered: Generated<boolean>;
  legal_name: string;
  logo_url: string | null;
  next_invoice_number: Generated<number>;
  owner_id: string;
  pan: string | null;
  phone: string | null;
  pincode: string | null;
  postal_code: string | null;
  region: string | null;
  routing_number: string | null;
  signature_url: string | null;
  state_code: string | null;
  /**
   * Optional VAT / EIN / GSTIN / ABN. No format check.
   */
  tax_id: string | null;
  trade_name: string | null;
  updated_at: Generated<string>;
  upi_id: string | null;
}

export interface CliDeviceCodes {
  api_key_id: string | null;
  approved_at: string | null;
  client_name: string;
  client_os: string | null;
  consumed_at: string | null;
  created_at: Generated<string>;
  device_code_hash: string;
  expires_at: Generated<string>;
  id: Generated<string>;
  last_polled_at: string | null;
  owner_id: string | null;
  scopes: Generated<string[]>;
  status: Generated<CliDeviceStatus>;
  user_code: string;
}

export interface Clients {
  address_line1: string | null;
  address_line2: string | null;
  /**
   * Soft delete. Issued invoices reference clients, so rows are never removed.
   */
  archived_at: string | null;
  city: string | null;
  country: Generated<string>;
  country_code: Generated<string | null>;
  created_at: Generated<string>;
  email: string | null;
  gstin: string | null;
  id: Generated<string>;
  name: string;
  owner_id: string;
  phone: string | null;
  pincode: string | null;
  postal_code: string | null;
  /**
   * API-facing customer id: cus_….
   */
  public_id: Generated<string>;
  region: string | null;
  state_code: string | null;
  tax_id: string | null;
  updated_at: Generated<string>;
}

export interface EmailVerifications {
  created_at: Generated<string>;
  email: string;
  expires_at: Generated<string>;
  id: Generated<string>;
  token_hash: string;
  used_at: string | null;
  user_id: string;
}

export interface IdempotencyKeys {
  created_at: Generated<string>;
  expires_at: Generated<string>;
  key: string;
  method: string;
  owner_id: string;
  path: string;
  request_hash: string;
  response_body: Json | null;
  response_status: number | null;
  state: Generated<string>;
}

export interface InvoiceEvents {
  created_at: Generated<string>;
  id: Generated<string>;
  invoice_id: string;
  meta: Generated<Json>;
  type: InvoiceEventType;
}

export interface InvoiceItems {
  cess_amount: Generated<Numeric>;
  cess_rate: Generated<Numeric>;
  cgst_amount: Generated<Numeric>;
  description: string;
  discount_percent: Generated<Numeric>;
  gst_rate: Generated<Numeric>;
  hsn_sac: string | null;
  id: Generated<string>;
  igst_amount: Generated<Numeric>;
  invoice_id: string;
  line_total: Generated<Numeric>;
  position: Generated<number>;
  price_id: string | null;
  product_id: string | null;
  /**
   * API-facing invoice item id: ii_….
   */
  public_id: Generated<string>;
  quantity: Generated<Numeric>;
  rate: Generated<Numeric>;
  sgst_amount: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  tax_rate: Generated<Numeric>;
  taxable_value: Generated<Numeric>;
  unit: Generated<string>;
}

export interface Invoices {
  amount_in_words: string | null;
  business_id: string;
  business_snapshot: Json | null;
  /**
   * Why the invoice was cancelled. Required by the service layer; an audit asks.
   */
  cancel_reason: string | null;
  cancelled_at: string | null;
  cess_total: Generated<Numeric>;
  cgst_total: Generated<Numeric>;
  client_id: string | null;
  client_snapshot: Json | null;
  /**
   * Stripe-style: charge_automatically or send_invoice. Stored; no auto-charging yet.
   */
  collection_method: Generated<string>;
  created_at: Generated<string>;
  currency: Generated<string>;
  discount_total: Generated<Numeric>;
  due_date: string | null;
  id: Generated<string>;
  igst_total: Generated<Numeric>;
  invoice_number: string | null;
  is_export: Generated<boolean>;
  issue_date: Generated<string>;
  notes: string | null;
  owner_id: string;
  paid_at: string | null;
  place_of_supply_state_code: string | null;
  /**
   * API-facing invoice id: in_….
   */
  public_id: Generated<string>;
  public_token: Generated<string>;
  reverse_charge: Generated<boolean>;
  round_off: Generated<Numeric>;
  sent_at: string | null;
  sgst_total: Generated<Numeric>;
  status: Generated<InvoiceStatus>;
  subtotal: Generated<Numeric>;
  tax_total: Generated<Numeric>;
  taxable_total: Generated<Numeric>;
  terms: string | null;
  total: Generated<Numeric>;
  updated_at: Generated<string>;
}

export interface OauthAuthorizationCodes {
  client_id: string;
  code_challenge: string;
  code_challenge_method: Generated<string>;
  code_hash: string;
  consumed_at: string | null;
  created_at: Generated<string>;
  expires_at: Generated<string>;
  grant_id: string;
  id: Generated<string>;
  owner_id: string;
  redirect_uri: string;
  replayed_at: string | null;
  resource: string;
  scopes: string[];
}

export interface OauthClients {
  client_id: string;
  client_name: string;
  client_secret_hash: string | null;
  client_uri: string | null;
  created_at: Generated<string>;
  grant_types: Generated<string[]>;
  id: Generated<string>;
  kind: string;
  last_used_at: string | null;
  logo_uri: string | null;
  metadata: Json | null;
  metadata_expires_at: string | null;
  redirect_uris: string[];
  token_endpoint_auth_method: string;
}

export interface OauthGrants {
  client_id: string;
  created_at: Generated<string>;
  id: Generated<string>;
  last_used_at: string | null;
  owner_id: string;
  revoked_at: string | null;
  scopes: string[];
  updated_at: Generated<string>;
}

export interface OauthTokens {
  created_at: Generated<string>;
  expires_at: string;
  family_id: string;
  grant_id: string;
  id: Generated<string>;
  kind: string;
  parent_id: string | null;
  resource: string;
  revoked_at: string | null;
  scopes: string[];
  token_hash: string;
  used_at: string | null;
}

export interface Prices {
  active: Generated<boolean>;
  created_at: Generated<string>;
  currency: string;
  id: Generated<string>;
  interval_count: Generated<number>;
  nickname: string | null;
  owner_id: string;
  product_id: string;
  public_id: string;
  recurring_interval: string | null;
  tax_rate: Generated<Numeric>;
  type: Generated<string>;
  unit_amount: Generated<Numeric>;
  updated_at: Generated<string>;
}

export interface Products {
  active: Generated<boolean>;
  created_at: Generated<string>;
  description: string | null;
  id: Generated<string>;
  images: Generated<Json>;
  name: string;
  owner_id: string;
  public_id: string;
  updated_at: Generated<string>;
}

export interface Profiles {
  created_at: Generated<string>;
  email: string | null;
  /**
   * When the user proved they own profiles.email. Null = unverified. Set only by SECURITY DEFINER functions; the guard trigger ignores client writes.
   */
  email_verified_at: string | null;
  full_name: string | null;
  id: string;
  /**
   * Null means the onboarding wizard has not been finished. The (app) layout gates on this.
   */
  onboarding_completed_at: string | null;
  /**
   * Which wizard step to resume at. Kept server-side so closing the tab mid-signup loses nothing.
   */
  onboarding_step: Generated<number>;
  updated_at: Generated<string>;
}

export interface WebhookDeliveries {
  attempt: Generated<number>;
  created_at: Generated<string>;
  endpoint_id: string;
  event_type: string;
  id: Generated<string>;
  last_error: string | null;
  next_attempt_at: Generated<string>;
  owner_id: string;
  payload: Json;
  response_code: number | null;
  status: Generated<string>;
}

export interface WebhookEndpoints {
  active: Generated<boolean>;
  created_at: Generated<string>;
  disabled_at: string | null;
  events: Generated<string[]>;
  failure_count: Generated<number>;
  id: Generated<string>;
  owner_id: string;
  secret: string;
  url: string;
}

export interface DB {
  api_keys: ApiKeys;
  api_requests: ApiRequests;
  businesses: Businesses;
  cli_device_codes: CliDeviceCodes;
  clients: Clients;
  email_verifications: EmailVerifications;
  idempotency_keys: IdempotencyKeys;
  invoice_events: InvoiceEvents;
  invoice_items: InvoiceItems;
  invoices: Invoices;
  oauth_authorization_codes: OauthAuthorizationCodes;
  oauth_clients: OauthClients;
  oauth_grants: OauthGrants;
  oauth_tokens: OauthTokens;
  prices: Prices;
  products: Products;
  profiles: Profiles;
  webhook_deliveries: WebhookDeliveries;
  webhook_endpoints: WebhookEndpoints;
}
