import { importJWK, importPKCS8, SignJWT, type JWK } from 'jose'

/**
 * Mint a short-lived Supabase-compatible access token.
 *
 * This function is the reason an API key is safe. The alternative — look the key
 * up, then query with the service_role key — bypasses RLS entirely, moving
 * tenant isolation out of the database and into every `.eq('owner_id', …)` a
 * developer might forget. Here, the key is exchanged for a token that says
 * "I am user X", and Postgres applies the same policies it applies to a browser.
 *
 *     Authorization: Bearer inv_live_ab12cd34_…
 *              │
 *              ▼  verify peppered HMAC, check not revoked/expired
 *              │
 *              ▼  sign { sub: owner_id, role: 'authenticated', exp: +60s }
 *              │     with OUR ES256 key, whose public half is imported
 *              │     into Supabase so it verifies our signature
 *              ▼
 *      supabase client → Postgres sees auth.uid() = owner_id → RLS applies
 *
 * The 60-second lifetime is deliberate. The token never leaves the server and is
 * minted per request, so there is no reason for it to outlive the request — a
 * leaked one is useless almost immediately.
 *
 * SECURITY: SUPABASE_JWT_PRIVATE_KEY is the most sensitive secret in the system.
 * Anything holding it can mint a token for *any* user id. Keep it in Vercel's
 * encrypted env only, never in the repo, and rotate it through Supabase's
 * signing-key UI rather than by editing it in place.
 */

const TOKEN_TTL_SECONDS = 60

export interface MintOptions {
  userId: string
  /** Recorded so an audit can tell which key minted a token. Not read by RLS. */
  apiKeyId?: string
  clientId?: string
}

export async function mintUserToken(options: MintOptions): Promise<string> {
  const { key, keyId } = await signingKey()

  return new SignJWT({
    // `role` is what Postgres switches into. It must be `authenticated` —
    // anything else, and every RLS policy (which is `to authenticated`) stops
    // matching and the request silently sees nothing.
    role: 'authenticated',
    // Supabase's own tokens carry these; some helpers and policies read them.
    aud: 'authenticated',
    ...(options.apiKeyId ? { api_key_id: options.apiKeyId } : {}),
    ...(options.clientId ? { client_id: options.clientId } : {}),
  })
    .setProtectedHeader({ alg: 'ES256', kid: keyId, typ: 'JWT' })
    .setSubject(options.userId)
    .setIssuedAt()
    .setExpirationTime(`${TOKEN_TTL_SECONDS}s`)
    .sign(key)
}

/** True when the environment is configured to mint tokens at all. */
export function canMintTokens(): boolean {
  return Boolean(
    process.env.SUPABASE_JWT_KID &&
      (process.env.SUPABASE_JWT_PRIVATE_KEY_JWK || process.env.SUPABASE_JWT_PRIVATE_KEY),
  )
}

/**
 * Two accepted formats, because the two tools that produce this key disagree.
 *
 * Supabase's Management API takes and returns a **JWK**, so `scripts/setup-api.ts`
 * naturally has one — that is the preferred form. A PEM is still accepted for a
 * key generated by `supabase gen signing-key`, which emits PKCS8.
 */
async function signingKey(): Promise<{ key: CryptoKey | Uint8Array; keyId: string }> {
  const keyId = process.env.SUPABASE_JWT_KID
  const jwk = process.env.SUPABASE_JWT_PRIVATE_KEY_JWK
  const pem = process.env.SUPABASE_JWT_PRIVATE_KEY

  if (!keyId || (!jwk && !pem)) {
    throw new Error(
      'SUPABASE_JWT_KID and one of SUPABASE_JWT_PRIVATE_KEY_JWK / SUPABASE_JWT_PRIVATE_KEY must be set ' +
        'to authenticate API keys. Run `pnpm api:setup` to generate and import one.',
    )
  }

  if (jwk) {
    return { key: await importJWK(forSigning(JSON.parse(jwk) as JWK), 'ES256'), keyId }
  }

  // Vercel env vars can't hold literal newlines, so a PEM is usually stored with
  // \n escapes. Normalising here means both forms work.
  return { key: await importPKCS8(pem!.replace(/\\n/g, '\n'), 'ES256'), keyId }
}

/**
 * Strip the key-usage hints before importing.
 *
 * Supabase's Management API requires `key_ops: ["sign", "verify"]` on the JWK it
 * accepts — its schema pins exactly those two. WebCrypto disagrees: a *private*
 * EC key may only declare `sign`, and importing one that also claims `verify`
 * throws "Unsupported key usage for a ECDSA key".
 *
 * Both are right about their own side, so the same JWK simply cannot satisfy
 * both. Dropping the hints here lets jose infer usage from the key material,
 * which is what it does anyway.
 */
function forSigning(jwk: JWK): JWK {
  const copy: JWK = { ...jwk }
  delete copy.key_ops
  delete copy.use
  return copy
}
